### PR TITLE
Added usage to README

### LINKED ISSUE #2: Update Documentation
> This library has been updated, though the documentation has not been updated. 

## About 
This is a little utility library for converting JSON data to CSV format. For now, the application creates a CSV format string from the JSON data, for example: 

JSON
```js
const data = [
{"language": "javascript", "rating": 5},
{"language": "java", "rating": 5}
]
```

CSV
```js
const data = `
language, rating
javascript, 5
java, 5
`
```

## TODO
- [ ] Update the readme section with a usage section giving example about what how to use the library
- [ ] Read the `src/core.ts` file and create suitable examples with explanations.

### PR DESCRIPTION
**Pull request by hnishal**
fixes #2 
I'm skeptical about third example

### CODE REVIEW

**Review by Souvikns — CHANGES_REQUESTED** [review]
The examples are fine, for understanding what the input and output format is. But as this is a library it would be good to have the API for the library, like how to make the object and which function to call. 

Go through [this](https://github.com/Ninja-Developers/jsv-convert/blob/master/src/core.ts) code to understand what the class is doing. 
### I can give you a basic idea of using the class
```ts
import {FileConverter} from 'jsv-convert'
import path from 'path'

const fc = new FileConverter(path.join(__dirname,'data.json')) // takes path of the file as a parameter

console.log(fc.generateCsvFormat())
```

**Comment by hnishal** [comment]
@Souvikns, so with those examples I need to include the whole code, importing and calling instance methods?

**Comment by Souvikns** [comment]
Not the whole code but just how to use the library. Like how the end-user will use. 
Check [this](https://github.com/aweary/tinytime) for example, how the API is documented for the user to understand how to use the library.

**Comment by hnishal** [comment]
@Souvikns please let me know if i did things right

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
